apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: reddo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: localhost/worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres.reddo.svc.cluster.local:5432/reddo?sslmode=disable"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq.reddo.svc.cluster.local:5672/"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
